# Generated by Django 3.1.12 on 2024-11-24 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20241119_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.CharField(max_length=255)),
                ('food_name', models.CharField(max_length=100)),
                ('quantity', models.FloatField(default=0)),
                ('grade', models.CharField(max_length=2)),
                ('calories', models.FloatField(default=0)),
                ('proteins', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('fiber', models.FloatField(default=0)),
                ('sugar', models.FloatField(default=0)),
                ('ingredients', djongo.models.fields.JSONField(default=list)),
                ('api_response', djongo.models.fields.JSONField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'food_entries',
                'ordering': ['-date_added'],
            },
        ),
    ]
